[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
eth_rpc_url = "https://eth-goerli.g.alchemy.com/v2/TpEOyDI0hxgwyGwn_0CdgZVg_eFXRfaX"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config